# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp_resources/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newNoteBtn = QtWidgets.QPushButton(self.widget_3)
        self.newNoteBtn.setObjectName("newNoteBtn")
        self.verticalLayout.addWidget(self.newNoteBtn)
        self.newLabelBtn = QtWidgets.QPushButton(self.widget_3)
        self.newLabelBtn.setObjectName("newLabelBtn")
        self.verticalLayout.addWidget(self.newLabelBtn)
        self.labelsListWidget = QtWidgets.QListWidget(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelsListWidget.setFont(font)
        self.labelsListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelsListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelsListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelsListWidget.setAutoFillBackground(False)
        self.labelsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.labelsListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.labelsListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.labelsListWidget.setDragEnabled(False)
        self.labelsListWidget.setDragDropOverwriteMode(False)
        self.labelsListWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.labelsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.labelsListWidget.setProperty("isWrapping", False)
        self.labelsListWidget.setObjectName("labelsListWidget")
        self.verticalLayout.addWidget(self.labelsListWidget)
        self.deleteLabelBtn = QtWidgets.QPushButton(self.widget_3)
        self.deleteLabelBtn.setObjectName("deleteLabelBtn")
        self.verticalLayout.addWidget(self.deleteLabelBtn)
        self.verticalLayout.setStretch(2, 12)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notesLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.notesLabel.setFont(font)
        self.notesLabel.setText("")
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout_2.addWidget(self.notesLabel)
        self.notesListWidget = QtWidgets.QListWidget(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.notesListWidget.setFont(font)
        self.notesListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.notesListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.notesListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.notesListWidget.setAutoFillBackground(False)
        self.notesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notesListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.notesListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.notesListWidget.setDragEnabled(False)
        self.notesListWidget.setDragDropOverwriteMode(False)
        self.notesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.notesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.notesListWidget.setObjectName("notesListWidget")
        self.verticalLayout_2.addWidget(self.notesListWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 20)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titlEdit = QtWidgets.QLineEdit(self.widget)
        self.titlEdit.setObjectName("titlEdit")
        self.horizontalLayout_3.addWidget(self.titlEdit)
        self.favCheckBox = QtWidgets.QCheckBox(self.widget)
        self.favCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favCheckBox.setObjectName("favCheckBox")
        self.horizontalLayout_3.addWidget(self.favCheckBox)
        self.noteActionBtn = QtWidgets.QPushButton(self.widget)
        self.noteActionBtn.setObjectName("noteActionBtn")
        self.horizontalLayout_3.addWidget(self.noteActionBtn)
        self.editLabelsBtn = QtWidgets.QPushButton(self.widget)
        self.editLabelsBtn.setObjectName("editLabelsBtn")
        self.horizontalLayout_3.addWidget(self.editLabelsBtn)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.noteWidget = QtWidgets.QWidget(self.widget)
        self.noteWidget.setObjectName("noteWidget")
        self.verticalLayout_3.addWidget(self.noteWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newNoteBtn.setText(_translate("MainWindow", "New note"))
        self.newLabelBtn.setText(_translate("MainWindow", "New label"))
        self.deleteLabelBtn.setText(_translate("MainWindow", "Delete label"))
        self.titlEdit.setText(_translate("MainWindow", "Input title"))
        self.favCheckBox.setText(_translate("MainWindow", "Fav"))
        self.noteActionBtn.setText(_translate("MainWindow", "Render/Edit"))
        self.editLabelsBtn.setText(_translate("MainWindow", "Edit labels"))
