# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp_resources/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 618)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelsWidget = QtWidgets.QWidget(self.centralwidget)
        self.labelsWidget.setObjectName("labelsWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.labelsWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newLabelBtn = QtWidgets.QPushButton(self.labelsWidget)
        self.newLabelBtn.setAutoFillBackground(False)
        self.newLabelBtn.setStyleSheet("")
        self.newLabelBtn.setObjectName("newLabelBtn")
        self.verticalLayout.addWidget(self.newLabelBtn)
        self.labelsListWidget = QtWidgets.QListWidget(self.labelsWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelsListWidget.setFont(font)
        self.labelsListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelsListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelsListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelsListWidget.setAutoFillBackground(False)
        self.labelsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.labelsListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.labelsListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.labelsListWidget.setDragEnabled(False)
        self.labelsListWidget.setDragDropOverwriteMode(False)
        self.labelsListWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.labelsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.labelsListWidget.setProperty("isWrapping", False)
        self.labelsListWidget.setObjectName("labelsListWidget")
        self.verticalLayout.addWidget(self.labelsListWidget)
        self.deleteLabelBtn = QtWidgets.QPushButton(self.labelsWidget)
        self.deleteLabelBtn.setStyleSheet("")
        self.deleteLabelBtn.setObjectName("deleteLabelBtn")
        self.verticalLayout.addWidget(self.deleteLabelBtn)
        self.verticalLayout.setStretch(1, 12)
        self.horizontalLayout.addWidget(self.labelsWidget)
        self.previewWidget = QtWidgets.QWidget(self.centralwidget)
        self.previewWidget.setObjectName("previewWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.previewWidget)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchEdit = QtWidgets.QLineEdit(self.previewWidget)
        self.searchEdit.setText("")
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_2.addWidget(self.searchEdit)
        self.searchBtn = QtWidgets.QPushButton(self.previewWidget)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout_2.addWidget(self.searchBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.notesListWidget = QtWidgets.QListWidget(self.previewWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.notesListWidget.setFont(font)
        self.notesListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.notesListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.notesListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.notesListWidget.setAutoFillBackground(False)
        self.notesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notesListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.notesListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.notesListWidget.setDragEnabled(False)
        self.notesListWidget.setDragDropOverwriteMode(False)
        self.notesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.notesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.notesListWidget.setObjectName("notesListWidget")
        self.verticalLayout_2.addWidget(self.notesListWidget)
        self.horizontalLayout.addWidget(self.previewWidget)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newLabelBtn.setText(_translate("MainWindow", "New label"))
        self.deleteLabelBtn.setText(_translate("MainWindow", "Delete label"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Input text to search with"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
